# Generated by Django 4.2.6 on 2023-10-16 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('income', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Income', 'Income'), ('Expense', 'Expense')], max_length=100)),
                ('category', models.CharField(choices=[('Salary', 'Salary'), ('Business', 'Business'), ('Loan', 'Loan'), ('Others', 'Others'), ('Groceries', 'Groceries'), ('Food', 'Food'), ('Fuel', 'Fuel'), ('Tax', 'Tax'), ('Electricity', 'Electricity'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Loan', 'Loan'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Investment', 'Investment'), ('Rent', 'Rent'), ('Mobile Bills', 'Mobile Bills'), ('TV & OTT', 'TV & OTT'), ('EMI', 'EMI'), ('Others', 'Others')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.useraccount')),
            ],
        ),
    ]
