# Generated by Django 4.2.7 on 2023-11-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_record_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='category',
            field=models.CharField(choices=[('Interests', 'Interests'), ('Gifts', 'Gifts'), ('Salary', 'Salary'), ('Business', 'Business'), ('Rentals', 'Rentals'), ('Others', 'Others'), ('Groceries', 'Groceries'), ('Food', 'Food'), ('Fuel', 'Fuel'), ('Tax', 'Tax'), ('Electricity', 'Electricity'), ('Shopping', 'Shopping'), ('Travel', 'Travel'), ('Loan', 'Loan'), ('Entertainment', 'Entertainment'), ('Health', 'Health'), ('Investment', 'Investment'), ('Rent', 'Rent'), ('Mobile Bills', 'Mobile Bills'), ('TV & OTT', 'TV & OTT'), ('EMI', 'EMI'), ('Others', 'Others')], max_length=100),
        ),
    ]
